apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: my-laravel-app
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_DATABASE
              value: laravel
            - name: DB_USERNAME
              value: user
            - name: DB_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer
